USE [QLSVTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_LAY_DS_DKMH]    Script Date: 12/10/2024 2:34:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_LAY_DS_DKMH] @NienKhoa NCHAR(9), @HocKy INT, @Nhom INT, @MonHoc NCHAR(10)
	
AS
BEGIN
	DECLARE @LopTinChi INT

	SELECT TOP 1 @LopTinChi = LOPTINCHI.MALTC
	FROM LOPTINCHI join NKHK on LOPTINCHI.MANKHK=NKHK.MANKHK
	WHERE NAMHOC = @NienKhoa AND HK = @HocKy
	AND NHOM = @Nhom AND MAMH = @MonHoc

	SELECT @LopTinChi LOPTC, MASV,
	HOTEN = (SELECT HO + ' ' +TEN FROM SINHVIEN WHERE DK.MASV = SINHVIEN.MASV), 
	DIEM_CC, DIEM_GK, DIEM_CK, DIEM_TK = DIEM_CC*0.1 + DIEM_GK*0.3 + DIEM_CK*0.6 
	FROM (SELECT MASV, DIEM_CC, DIEM_GK, DIEM_CK FROM DANGKY WHERE MALTC = @LopTinChi AND 
	(HUYDANGKY=0 OR HUYDANGKY IS NULL)) DK
END

GO

