USE [QLSVTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_REPORT_PHIEU_DIEM_SV]    Script Date: 12/20/2024 2:28:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_REPORT_PHIEU_DIEM_SV]
    @MaSV NCHAR(10) -- Mã sinh viên
AS
BEGIN
    IF EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV=@MaSV)
		BEGIN
			SELECT LTC.TENMONHOC, 
                   DIEM = MAX(DIEM_CC * 0.1 + DIEM_GK * 0.3 + DIEM_CK * 0.6)
			FROM (SELECT MALTC, DIEM_CC, DIEM_CK, DIEM_GK 
				  FROM DANGKY 
				  WHERE MASV = @MaSV AND (DANGKY.HUYDANGKY = 0 OR DANGKY.HUYDANGKY IS NULL)) DK
			JOIN (SELECT LOPTINCHI.MALTC, MONHOC.TENMONHOC, MONHOC.MAMH
				  FROM LOPTINCHI 
				  JOIN MONHOC ON LOPTINCHI.MAMH = MONHOC.MAMH
				  WHERE LOPTINCHI.HUYLOP = 0) AS LTC ON DK.MALTC = LTC.MALTC
			GROUP BY LTC.TENMONHOC
			ORDER BY LTC.TENMONHOC
		END
	ELSE
		BEGIN
			RAISERROR('Sinh viên không t?n t?i', 16, 1);
			RETURN 0;
		END
END

GO

