USE [QLSVTC]
GO

/****** Object:  StoredProcedure [dbo].[SP_TAOLOGIN]    Script Date: 11/24/2024 7:40:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_TAOLOGIN] @LGNAME VARCHAR(50),
  @PASS VARCHAR(50),
  @USERNAME VARCHAR(50),
  @ROLE VARCHAR(50)
AS
  DECLARE @RET INT
  EXEC @RET= SP_ADDLOGIN @LGNAME, @PASS,'QLSVTC'
  IF (@RET =1)  -- LOGIN NAME BI TRUNG
     RETURN 1
 
  EXEC @RET= SP_GRANTDBACCESS @LGNAME, @USERNAME
  IF (@RET =1)  -- USER  NAME BI TRUNG
	BEGIN
		EXEC SP_DROPLOGIN @LGNAME
		RETURN 2
	END

  EXEC sp_addrolemember @ROLE, @USERNAME

  

  IF @ROLE= 'PGV' OR @ROLE= 'KHOA'
	BEGIN 
		
		EXEC sp_addsrvrolemember @LGNAME, 'SecurityAdmin'
		EXEC sp_addsrvrolemember @LGNAME, 'ProcessAdmin'
	END


	

	IF @ROLE= 'KHOA' 
	BEGIN 
		EXEC('GRANT UPDATE ON OBJECT::dbo.DANGKY' + @USERNAME)

		EXEC('GRANT INSERT ON OBJECT::dbo.LOPTINCHI TO ' + @USERNAME)
		EXEC('GRANT UPDATE ON OBJECT::dbo.LOPTINCHI TO ' + @USERNAME)

		EXEC('GRANT INSERT ON OBJECT::dbo.LOP TO ' + @USERNAME)
		EXEC('GRANT UPDATE ON OBJECT::dbo.LOP TO ' + @USERNAME)

		EXEC('GRANT INSERT ON OBJECT::dbo.SINHVIEN TO ' + @USERNAME)
		EXEC('GRANT UPDATE ON OBJECT::dbo.SINHVIEN TO ' + @USERNAME)

		EXEC('GRANT INSERT ON OBJECT::dbo.GIANGVIEN TO ' + @USERNAME)
		EXEC('GRANT UPDATE ON OBJECT::dbo.GIANGVIEN TO ' + @USERNAME)

	END

	IF @ROLE= 'SV' 
	BEGIN 
		EXEC('GRANT INSERT ON OBJECT::dbo.DANGKY TO ' + @USERNAME)
		EXEC('GRANT UPDATE ON OBJECT::dbo.DANGKY TO ' + @USERNAME)
	END
RETURN 0  -- THANH CONG


GO

